// @generated by schema-rust

#[rustfmt::skip]
pub type String = std::string::String;
#[rustfmt::skip]
pub type Integer = u64;
#[rustfmt::skip]
pub type Boolean = bool;
#[rustfmt::skip]
pub type Path = std::string::String;

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
pub use nota::{NotaDecodeError, NotaEncode, NotaSource};

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Operation {
    Generate(GenerationRequest),
    Visualize(VisualizationRequest),
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum GenerationOutcome {
    Generated(GenerationReport),
    Visualized(VisualizationReport),
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct GenerationRequest {
    pub source_root: SourceRoot,
    pub workspace_root: WorkspaceRoot,
    pub manifest_path: ManifestPath,
    pub generation_mode: GenerationMode,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct VisualizationRequest {
    pub source_root: SourceRoot,
    pub workspace_root: WorkspaceRoot,
    pub manifest_path: ManifestPath,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SourceRoot(Path);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct WorkspaceRoot(Path);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ManifestPath(Path);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum GenerationMode {
    Write,
    Check,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct GenerationReport(GeneratedFiles);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct GeneratedFiles(Vec<GeneratedFile>);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct GeneratedFile {
    pub output_path: OutputPath,
    pub byte_count: ByteCount,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct VisualizationReport {
    pub role_visualizations: RoleVisualizations,
    pub generated_output_visualizations: GeneratedOutputVisualizations,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RoleVisualizations(Vec<RoleVisualization>);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RoleVisualization {
    pub output_identifier: OutputIdentifier,
    pub role_packet_compositions: RolePacketCompositions,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RolePacketCompositions(Vec<RolePacketComposition>);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RolePacketComposition {
    pub output_path: OutputPath,
    pub output_surface: OutputSurface,
    pub modules: Modules,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct GeneratedOutputVisualizations(Vec<GeneratedOutputVisualization>);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct GeneratedOutputVisualization {
    pub output_path: OutputPath,
    pub byte_count: ByteCount,
    pub line_count: LineCount,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct OutputPath(Path);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ByteCount(Integer);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct LineCount(Integer);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Manifest {
    pub output_path: OutputPath,
    pub output_kind: OutputKind,
    pub output_surface: OutputSurface,
    pub frontmatter: Frontmatter,
    pub modules: Modules,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum OutputKind {
    Markdown,
    Nota,
    Toml,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum OutputSurface {
    Workspace,
    AgentsSkill,
    ClaudeSkill,
    ClaudeAgent,
    CodexAgent,
    PiAgent,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Frontmatter(Vec<FrontmatterEntry>);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct FrontmatterEntry {
    pub frontmatter_key: FrontmatterKey,
    pub frontmatter_value: FrontmatterValue,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct FrontmatterKey(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct FrontmatterValue(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ModulePath(Path);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Modules(Vec<ModulePath>);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ActiveOutputs(Vec<ActiveOutput>);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum ActiveOutput {
    Skill(ActiveSkill),
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ActiveSkill {
    pub output_identifier: OutputIdentifier,
    pub module_identifier: ModuleIdentifier,
    pub skill_category: SkillCategory,
    pub skill_tier: SkillTier,
    pub skill_description: SkillDescription,
    pub target_surfaces: TargetSurfaces,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Debug,
    PartialEq,
    Eq,
    PartialOrd,
    Ord,
)]
#[rkyv(derive(PartialEq, Eq, PartialOrd, Ord))]
pub struct OutputIdentifier(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Debug,
    PartialEq,
    Eq,
    PartialOrd,
    Ord,
)]
#[rkyv(derive(PartialEq, Eq, PartialOrd, Ord))]
pub struct ModuleIdentifier(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct IncludedModules(Vec<ModuleIdentifier>);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RoleDescription(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum RoleTargetSurface {
    ClaudeAgent,
    CodexAgent,
    PiAgent,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ModelCatalog(Vec<ModelCatalogEntry>);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ModelCatalogEntry {
    pub model_identifier: ModelIdentifier,
    pub provider_surface: ProviderSurface,
    pub accepted_effort_levels: AcceptedEffortLevels,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Debug,
    PartialEq,
    Eq,
    PartialOrd,
    Ord,
)]
#[rkyv(derive(PartialEq, Eq, PartialOrd, Ord))]
pub struct ModelIdentifier(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum ProviderSurface {
    Claude,
    ChatGpt,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct AcceptedEffortLevels(Vec<EffortLevel>);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum EffortLevel {
    Low,
    Medium,
    High,
    Xhigh,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RolePermissions(Vec<RolePermission>);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RolePermission {
    pub role_permission_identifier: RolePermissionIdentifier,
    pub permission_body: PermissionBody,
    pub tool_restriction: ToolRestriction,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Debug,
    PartialEq,
    Eq,
    PartialOrd,
    Ord,
)]
#[rkyv(derive(PartialEq, Eq, PartialOrd, Ord))]
pub struct RolePermissionIdentifier(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct PermissionBody(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum ToolRestriction {
    Restricted,
    Unrestricted,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RoleDepths(Vec<RoleDepth>);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RoleDepth {
    pub role_depth_identifier: RoleDepthIdentifier,
    pub claude_depth_model: ClaudeDepthModel,
    pub chat_gpt_depth_model: ChatGptDepthModel,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Debug,
    PartialEq,
    Eq,
    PartialOrd,
    Ord,
)]
#[rkyv(derive(PartialEq, Eq, PartialOrd, Ord))]
pub struct RoleDepthIdentifier(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ClaudeDepthModel {
    pub model_identifier: ModelIdentifier,
    pub depth_effort_level: DepthEffortLevel,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ChatGptDepthModel {
    pub model_identifier: ModelIdentifier,
    pub depth_effort_level: DepthEffortLevel,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct DepthEffortLevel(Option<EffortLevel>);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RoleDescriptions(Vec<RoleDescriptionCell>);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RoleDescriptionCell {
    pub role_permission_identifier: RolePermissionIdentifier,
    pub role_depth_identifier: RoleDepthIdentifier,
    pub role_description: RoleDescription,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ModuleDependencies(Vec<ModuleDependency>);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct UniversalRoleModules(Vec<ModuleIdentifier>);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SkillModuleCompositions(Vec<SkillModuleComposition>);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SkillModuleComposition {
    pub output_identifier: OutputIdentifier,
    pub included_modules: IncludedModules,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ModuleDependency {
    pub module_identifier: ModuleIdentifier,
    pub module_path: ModulePath,
    pub dependency_modules: DependencyModules,
    pub module_kind: ModuleKind,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum ModuleKind {
    RuntimeSkill,
    RoleComposition,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct DependencyModules(Vec<ModuleIdentifier>);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct TargetModuleInsertions(Vec<TargetModuleInsertion>);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct TargetModuleInsertion {
    pub module_identifier: ModuleIdentifier,
    pub output_surface: OutputSurface,
    pub included_modules: IncludedModules,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct GeneratedRoleOutputs(Vec<OutputPath>);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum SkillCategory {
    Architecture,
    Craft,
    Programming,
    Workflow,
    Meta,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum SkillTier {
    Apex,
    Keystroke,
    Topic,
    Mechanism,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SkillDescription(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct TargetSurfaces(Vec<TargetSurface>);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum TargetSurface {
    AgentsSkill,
    ClaudeSkill,
}

#[rustfmt::skip]
impl SourceRoot {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &Path {
        &self.0
    }
    pub fn into_payload(self) -> Path {
        self.0
    }
}
#[rustfmt::skip]
impl From<Path> for SourceRoot {
    fn from(payload: Path) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl WorkspaceRoot {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &Path {
        &self.0
    }
    pub fn into_payload(self) -> Path {
        self.0
    }
}
#[rustfmt::skip]
impl From<Path> for WorkspaceRoot {
    fn from(payload: Path) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ManifestPath {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &Path {
        &self.0
    }
    pub fn into_payload(self) -> Path {
        self.0
    }
}
#[rustfmt::skip]
impl From<Path> for ManifestPath {
    fn from(payload: Path) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl GenerationReport {
    pub fn new(payload: GeneratedFiles) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &GeneratedFiles {
        &self.0
    }
    pub fn into_payload(self) -> GeneratedFiles {
        self.0
    }
}
#[rustfmt::skip]
impl From<GeneratedFiles> for GenerationReport {
    fn from(payload: GeneratedFiles) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl GeneratedFiles {
    pub fn new(payload: Vec<GeneratedFile>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Vec<GeneratedFile> {
        &self.0
    }
    pub fn into_payload(self) -> Vec<GeneratedFile> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Vec<GeneratedFile>> for GeneratedFiles {
    fn from(payload: Vec<GeneratedFile>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl RoleVisualizations {
    pub fn new(payload: Vec<RoleVisualization>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Vec<RoleVisualization> {
        &self.0
    }
    pub fn into_payload(self) -> Vec<RoleVisualization> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Vec<RoleVisualization>> for RoleVisualizations {
    fn from(payload: Vec<RoleVisualization>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl RolePacketCompositions {
    pub fn new(payload: Vec<RolePacketComposition>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Vec<RolePacketComposition> {
        &self.0
    }
    pub fn into_payload(self) -> Vec<RolePacketComposition> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Vec<RolePacketComposition>> for RolePacketCompositions {
    fn from(payload: Vec<RolePacketComposition>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl GeneratedOutputVisualizations {
    pub fn new(payload: Vec<GeneratedOutputVisualization>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Vec<GeneratedOutputVisualization> {
        &self.0
    }
    pub fn into_payload(self) -> Vec<GeneratedOutputVisualization> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Vec<GeneratedOutputVisualization>> for GeneratedOutputVisualizations {
    fn from(payload: Vec<GeneratedOutputVisualization>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl OutputPath {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &Path {
        &self.0
    }
    pub fn into_payload(self) -> Path {
        self.0
    }
}
#[rustfmt::skip]
impl From<Path> for OutputPath {
    fn from(payload: Path) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ByteCount {
    pub fn new(payload: Integer) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Integer {
        &self.0
    }
    pub fn into_payload(self) -> Integer {
        self.0
    }
}
#[rustfmt::skip]
impl From<Integer> for ByteCount {
    fn from(payload: Integer) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl LineCount {
    pub fn new(payload: Integer) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Integer {
        &self.0
    }
    pub fn into_payload(self) -> Integer {
        self.0
    }
}
#[rustfmt::skip]
impl From<Integer> for LineCount {
    fn from(payload: Integer) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Frontmatter {
    pub fn new(payload: Vec<FrontmatterEntry>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Vec<FrontmatterEntry> {
        &self.0
    }
    pub fn into_payload(self) -> Vec<FrontmatterEntry> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Vec<FrontmatterEntry>> for Frontmatter {
    fn from(payload: Vec<FrontmatterEntry>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl FrontmatterKey {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for FrontmatterKey {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl FrontmatterValue {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for FrontmatterValue {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ModulePath {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &Path {
        &self.0
    }
    pub fn into_payload(self) -> Path {
        self.0
    }
}
#[rustfmt::skip]
impl From<Path> for ModulePath {
    fn from(payload: Path) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Modules {
    pub fn new(payload: Vec<ModulePath>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Vec<ModulePath> {
        &self.0
    }
    pub fn into_payload(self) -> Vec<ModulePath> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Vec<ModulePath>> for Modules {
    fn from(payload: Vec<ModulePath>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ActiveOutputs {
    pub fn new(payload: Vec<ActiveOutput>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Vec<ActiveOutput> {
        &self.0
    }
    pub fn into_payload(self) -> Vec<ActiveOutput> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Vec<ActiveOutput>> for ActiveOutputs {
    fn from(payload: Vec<ActiveOutput>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl OutputIdentifier {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for OutputIdentifier {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ModuleIdentifier {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for ModuleIdentifier {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl IncludedModules {
    pub fn new(payload: Vec<ModuleIdentifier>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Vec<ModuleIdentifier> {
        &self.0
    }
    pub fn into_payload(self) -> Vec<ModuleIdentifier> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Vec<ModuleIdentifier>> for IncludedModules {
    fn from(payload: Vec<ModuleIdentifier>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl RoleDescription {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for RoleDescription {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ModelCatalog {
    pub fn new(payload: Vec<ModelCatalogEntry>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Vec<ModelCatalogEntry> {
        &self.0
    }
    pub fn into_payload(self) -> Vec<ModelCatalogEntry> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Vec<ModelCatalogEntry>> for ModelCatalog {
    fn from(payload: Vec<ModelCatalogEntry>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ModelIdentifier {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for ModelIdentifier {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl AcceptedEffortLevels {
    pub fn new(payload: Vec<EffortLevel>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Vec<EffortLevel> {
        &self.0
    }
    pub fn into_payload(self) -> Vec<EffortLevel> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Vec<EffortLevel>> for AcceptedEffortLevels {
    fn from(payload: Vec<EffortLevel>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl RolePermissions {
    pub fn new(payload: Vec<RolePermission>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Vec<RolePermission> {
        &self.0
    }
    pub fn into_payload(self) -> Vec<RolePermission> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Vec<RolePermission>> for RolePermissions {
    fn from(payload: Vec<RolePermission>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl RolePermissionIdentifier {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for RolePermissionIdentifier {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl PermissionBody {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for PermissionBody {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl RoleDepths {
    pub fn new(payload: Vec<RoleDepth>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Vec<RoleDepth> {
        &self.0
    }
    pub fn into_payload(self) -> Vec<RoleDepth> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Vec<RoleDepth>> for RoleDepths {
    fn from(payload: Vec<RoleDepth>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl RoleDepthIdentifier {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for RoleDepthIdentifier {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl DepthEffortLevel {
    pub fn new(payload: Option<EffortLevel>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Option<EffortLevel> {
        &self.0
    }
    pub fn into_payload(self) -> Option<EffortLevel> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Option<EffortLevel>> for DepthEffortLevel {
    fn from(payload: Option<EffortLevel>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl RoleDescriptions {
    pub fn new(payload: Vec<RoleDescriptionCell>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Vec<RoleDescriptionCell> {
        &self.0
    }
    pub fn into_payload(self) -> Vec<RoleDescriptionCell> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Vec<RoleDescriptionCell>> for RoleDescriptions {
    fn from(payload: Vec<RoleDescriptionCell>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ModuleDependencies {
    pub fn new(payload: Vec<ModuleDependency>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Vec<ModuleDependency> {
        &self.0
    }
    pub fn into_payload(self) -> Vec<ModuleDependency> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Vec<ModuleDependency>> for ModuleDependencies {
    fn from(payload: Vec<ModuleDependency>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl UniversalRoleModules {
    pub fn new(payload: Vec<ModuleIdentifier>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Vec<ModuleIdentifier> {
        &self.0
    }
    pub fn into_payload(self) -> Vec<ModuleIdentifier> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Vec<ModuleIdentifier>> for UniversalRoleModules {
    fn from(payload: Vec<ModuleIdentifier>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl SkillModuleCompositions {
    pub fn new(payload: Vec<SkillModuleComposition>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Vec<SkillModuleComposition> {
        &self.0
    }
    pub fn into_payload(self) -> Vec<SkillModuleComposition> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Vec<SkillModuleComposition>> for SkillModuleCompositions {
    fn from(payload: Vec<SkillModuleComposition>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl DependencyModules {
    pub fn new(payload: Vec<ModuleIdentifier>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Vec<ModuleIdentifier> {
        &self.0
    }
    pub fn into_payload(self) -> Vec<ModuleIdentifier> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Vec<ModuleIdentifier>> for DependencyModules {
    fn from(payload: Vec<ModuleIdentifier>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl TargetModuleInsertions {
    pub fn new(payload: Vec<TargetModuleInsertion>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Vec<TargetModuleInsertion> {
        &self.0
    }
    pub fn into_payload(self) -> Vec<TargetModuleInsertion> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Vec<TargetModuleInsertion>> for TargetModuleInsertions {
    fn from(payload: Vec<TargetModuleInsertion>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl GeneratedRoleOutputs {
    pub fn new(payload: Vec<OutputPath>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Vec<OutputPath> {
        &self.0
    }
    pub fn into_payload(self) -> Vec<OutputPath> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Vec<OutputPath>> for GeneratedRoleOutputs {
    fn from(payload: Vec<OutputPath>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl SkillDescription {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for SkillDescription {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl TargetSurfaces {
    pub fn new(payload: Vec<TargetSurface>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Vec<TargetSurface> {
        &self.0
    }
    pub fn into_payload(self) -> Vec<TargetSurface> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Vec<TargetSurface>> for TargetSurfaces {
    fn from(payload: Vec<TargetSurface>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl std::fmt::Display for SourceRoot {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        self.payload().fmt(formatter)
    }
}

#[rustfmt::skip]
impl AsRef<str> for SourceRoot {
    fn as_ref(&self) -> &str {
        self.payload().as_str()
    }
}

#[rustfmt::skip]
impl PartialEq<&str> for SourceRoot {
    fn eq(&self, other: &&str) -> bool {
        self.payload() == other
    }
}

#[rustfmt::skip]
impl std::fmt::Display for WorkspaceRoot {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        self.payload().fmt(formatter)
    }
}

#[rustfmt::skip]
impl AsRef<str> for WorkspaceRoot {
    fn as_ref(&self) -> &str {
        self.payload().as_str()
    }
}

#[rustfmt::skip]
impl PartialEq<&str> for WorkspaceRoot {
    fn eq(&self, other: &&str) -> bool {
        self.payload() == other
    }
}

#[rustfmt::skip]
impl std::fmt::Display for ManifestPath {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        self.payload().fmt(formatter)
    }
}

#[rustfmt::skip]
impl AsRef<str> for ManifestPath {
    fn as_ref(&self) -> &str {
        self.payload().as_str()
    }
}

#[rustfmt::skip]
impl PartialEq<&str> for ManifestPath {
    fn eq(&self, other: &&str) -> bool {
        self.payload() == other
    }
}

#[rustfmt::skip]
impl std::fmt::Display for OutputPath {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        self.payload().fmt(formatter)
    }
}

#[rustfmt::skip]
impl AsRef<str> for OutputPath {
    fn as_ref(&self) -> &str {
        self.payload().as_str()
    }
}

#[rustfmt::skip]
impl PartialEq<&str> for OutputPath {
    fn eq(&self, other: &&str) -> bool {
        self.payload() == other
    }
}

#[rustfmt::skip]
impl std::fmt::Display for ByteCount {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        self.payload().fmt(formatter)
    }
}

#[rustfmt::skip]
impl PartialEq<u64> for ByteCount {
    fn eq(&self, other: &u64) -> bool {
        self.payload() == other
    }
}

#[rustfmt::skip]
impl PartialOrd<u64> for ByteCount {
    fn partial_cmp(&self, other: &u64) -> Option<std::cmp::Ordering> {
        self.payload().partial_cmp(other)
    }
}

#[rustfmt::skip]
impl std::fmt::Display for LineCount {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        self.payload().fmt(formatter)
    }
}

#[rustfmt::skip]
impl PartialEq<u64> for LineCount {
    fn eq(&self, other: &u64) -> bool {
        self.payload() == other
    }
}

#[rustfmt::skip]
impl PartialOrd<u64> for LineCount {
    fn partial_cmp(&self, other: &u64) -> Option<std::cmp::Ordering> {
        self.payload().partial_cmp(other)
    }
}

#[rustfmt::skip]
impl std::fmt::Display for FrontmatterKey {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        self.payload().fmt(formatter)
    }
}

#[rustfmt::skip]
impl AsRef<str> for FrontmatterKey {
    fn as_ref(&self) -> &str {
        self.payload().as_str()
    }
}

#[rustfmt::skip]
impl PartialEq<&str> for FrontmatterKey {
    fn eq(&self, other: &&str) -> bool {
        self.payload() == other
    }
}

#[rustfmt::skip]
impl std::fmt::Display for FrontmatterValue {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        self.payload().fmt(formatter)
    }
}

#[rustfmt::skip]
impl AsRef<str> for FrontmatterValue {
    fn as_ref(&self) -> &str {
        self.payload().as_str()
    }
}

#[rustfmt::skip]
impl PartialEq<&str> for FrontmatterValue {
    fn eq(&self, other: &&str) -> bool {
        self.payload() == other
    }
}

#[rustfmt::skip]
impl std::fmt::Display for ModulePath {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        self.payload().fmt(formatter)
    }
}

#[rustfmt::skip]
impl AsRef<str> for ModulePath {
    fn as_ref(&self) -> &str {
        self.payload().as_str()
    }
}

#[rustfmt::skip]
impl PartialEq<&str> for ModulePath {
    fn eq(&self, other: &&str) -> bool {
        self.payload() == other
    }
}

#[rustfmt::skip]
impl std::fmt::Display for OutputIdentifier {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        self.payload().fmt(formatter)
    }
}

#[rustfmt::skip]
impl AsRef<str> for OutputIdentifier {
    fn as_ref(&self) -> &str {
        self.payload().as_str()
    }
}

#[rustfmt::skip]
impl PartialEq<&str> for OutputIdentifier {
    fn eq(&self, other: &&str) -> bool {
        self.payload() == other
    }
}

#[rustfmt::skip]
impl std::fmt::Display for ModuleIdentifier {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        self.payload().fmt(formatter)
    }
}

#[rustfmt::skip]
impl AsRef<str> for ModuleIdentifier {
    fn as_ref(&self) -> &str {
        self.payload().as_str()
    }
}

#[rustfmt::skip]
impl PartialEq<&str> for ModuleIdentifier {
    fn eq(&self, other: &&str) -> bool {
        self.payload() == other
    }
}

#[rustfmt::skip]
impl std::fmt::Display for RoleDescription {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        self.payload().fmt(formatter)
    }
}

#[rustfmt::skip]
impl AsRef<str> for RoleDescription {
    fn as_ref(&self) -> &str {
        self.payload().as_str()
    }
}

#[rustfmt::skip]
impl PartialEq<&str> for RoleDescription {
    fn eq(&self, other: &&str) -> bool {
        self.payload() == other
    }
}

#[rustfmt::skip]
impl std::fmt::Display for ModelIdentifier {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        self.payload().fmt(formatter)
    }
}

#[rustfmt::skip]
impl AsRef<str> for ModelIdentifier {
    fn as_ref(&self) -> &str {
        self.payload().as_str()
    }
}

#[rustfmt::skip]
impl PartialEq<&str> for ModelIdentifier {
    fn eq(&self, other: &&str) -> bool {
        self.payload() == other
    }
}

#[rustfmt::skip]
impl std::fmt::Display for RolePermissionIdentifier {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        self.payload().fmt(formatter)
    }
}

#[rustfmt::skip]
impl AsRef<str> for RolePermissionIdentifier {
    fn as_ref(&self) -> &str {
        self.payload().as_str()
    }
}

#[rustfmt::skip]
impl PartialEq<&str> for RolePermissionIdentifier {
    fn eq(&self, other: &&str) -> bool {
        self.payload() == other
    }
}

#[rustfmt::skip]
impl std::fmt::Display for PermissionBody {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        self.payload().fmt(formatter)
    }
}

#[rustfmt::skip]
impl AsRef<str> for PermissionBody {
    fn as_ref(&self) -> &str {
        self.payload().as_str()
    }
}

#[rustfmt::skip]
impl PartialEq<&str> for PermissionBody {
    fn eq(&self, other: &&str) -> bool {
        self.payload() == other
    }
}

#[rustfmt::skip]
impl std::fmt::Display for RoleDepthIdentifier {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        self.payload().fmt(formatter)
    }
}

#[rustfmt::skip]
impl AsRef<str> for RoleDepthIdentifier {
    fn as_ref(&self) -> &str {
        self.payload().as_str()
    }
}

#[rustfmt::skip]
impl PartialEq<&str> for RoleDepthIdentifier {
    fn eq(&self, other: &&str) -> bool {
        self.payload() == other
    }
}

#[rustfmt::skip]
impl std::fmt::Display for SkillDescription {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        self.payload().fmt(formatter)
    }
}

#[rustfmt::skip]
impl AsRef<str> for SkillDescription {
    fn as_ref(&self) -> &str {
        self.payload().as_str()
    }
}

#[rustfmt::skip]
impl PartialEq<&str> for SkillDescription {
    fn eq(&self, other: &&str) -> bool {
        self.payload() == other
    }
}

#[rustfmt::skip]
impl Operation {
    pub fn generate(payload: GenerationRequest) -> Self {
        Self::Generate(payload)
    }
    pub fn visualize(payload: VisualizationRequest) -> Self {
        Self::Visualize(payload)
    }
}

#[rustfmt::skip]
impl GenerationOutcome {
    pub fn generated(payload: GeneratedFiles) -> Self {
        Self::Generated(GenerationReport::new(payload))
    }
    pub fn visualized(payload: VisualizationReport) -> Self {
        Self::Visualized(payload)
    }
}

#[rustfmt::skip]
impl ActiveOutput {
    pub fn skill(payload: ActiveSkill) -> Self {
        Self::Skill(payload)
    }
}

#[rustfmt::skip]
impl From<GenerationRequest> for Operation {
    fn from(payload: GenerationRequest) -> Self {
        Self::Generate(payload)
    }
}

#[rustfmt::skip]
impl From<VisualizationRequest> for Operation {
    fn from(payload: VisualizationRequest) -> Self {
        Self::Visualize(payload)
    }
}

#[rustfmt::skip]
impl From<GenerationReport> for GenerationOutcome {
    fn from(payload: GenerationReport) -> Self {
        Self::Generated(payload)
    }
}

#[rustfmt::skip]
impl From<VisualizationReport> for GenerationOutcome {
    fn from(payload: VisualizationReport) -> Self {
        Self::Visualized(payload)
    }
}

#[rustfmt::skip]
impl From<ActiveSkill> for ActiveOutput {
    fn from(payload: ActiveSkill) -> Self {
        Self::Skill(payload)
    }
}
